### ISSUE TITLE
I want to test your code, but something went wrong in train.py

### ISSUE THREAD

**Issue by nightsky37** [loadder/MS_LSTM#3]
```
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    w = open('./logs/merge_tes_40attn.log', 'w')
FileNotFoundError: [Errno 2] No such file or directory: './logs/merge_tes_40attn.log'
```
It seems no file named "logs". Could you provide it? Thank you.

**Comment by chmxu** [comment]
You can simply create a 'logs' directory. I think this will work.

**Comment by xiaolongtuan-yuan** [comment]
when I run train.py
i got this error:

ModuleNotFoundError: No module named 'torch.nn._functions'

and i didn't find this module in pytorch's ducument

**Comment by chmxu** [comment]
> when I run train.py i got this error:
> 
> ModuleNotFoundError: No module named 'torch.nn._functions'
> 
> and i didn't find this module in pytorch's ducument

Hi, can you provide an error log? I guess there is something wrong with your installation of pytorch or the version of that.

**Comment by xiaolongtuan-yuan** [comment]
> 



> 

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from model import Scoring
  File "/content/drive/MyDrive/MS_LSTM/model.py", line 7, in <module>
    from util.graph_definition import *
  File "/content/drive/MyDrive/MS_LSTM/util/graph_definition.py", line 13, in <module>
    from rnn_cells.base_rnn import custom_LSTM
  File "/content/drive/MyDrive/MS_LSTM/rnn_cells/base_rnn.py", line 8, in <module>
    from rnn_cells.functions_rnn import custom_RNN as backend_custom_RNN
  File "/content/drive/MyDrive/MS_LSTM/rnn_cells/functions_rnn.py", line 4, in <module>
    from torch.nn._functions.rnn import LSTMCell, GRUCell
ModuleNotFoundError: No module named 'torch.nn._functions'

**Comment by xiaolongtuan-yuan** [comment]
> > when I run train.py i got this error:
> > ModuleNotFoundError: No module named 'torch.nn._functions'
> > and i didn't find this module in pytorch's ducument
> 
> Hi, can you provide an error log? I guess there is something wrong with your installation of pytorch or the version of that.

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from model import Scoring
  File "/content/drive/MyDrive/MS_LSTM/model.py", line 7, in <module>
    from util.graph_definition import *
  File "/content/drive/MyDrive/MS_LSTM/util/graph_definition.py", line 13, in <module>
    from rnn_cells.base_rnn import custom_LSTM
  File "/content/drive/MyDrive/MS_LSTM/rnn_cells/base_rnn.py", line 8, in <module>
    from rnn_cells.functions_rnn import custom_RNN as backend_custom_RNN
  File "/content/drive/MyDrive/MS_LSTM/rnn_cells/functions_rnn.py", line 4, in <module>
    from torch.nn._functions.rnn import LSTMCell, GRUCell
ModuleNotFoundError: No module named 'torch.nn._functions'

**Comment by chmxu** [comment]
I have checked that pytorch 0.4.0 has this module but the latest version has changed that. I think changing your version to 0.4.0/updating the code according to your version (e.g. find the corresponding LSTMCell module in the latest version) can work this problem out.
